<?php
// Auto-generated menu data from Avanti Menu.csv
$theme_uri = get_template_directory_uri();
$menu_items_array = array(
    array(
        'id'          => '1',
        'name'        => 'Masala Poteto Wedges',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '8 Pcs',
        'description' => 'Deep Fried Potato wedges served with Chef special sauce',
        'price'       => '172.8',
        'image'       => $theme_uri . '/assets/menu/masala-potato-wedges.png',
        'featured'    => false
    ),
    array(
        'id'          => '2',
        'name'        => 'Vegetable Spring Roll',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Vegetable Stuffing roll served with sweet chilli sauce',
        'price'       => '280.8',
        'image'       => $theme_uri . '/assets/menu/vegetable-spring-roll.png',
        'featured'    => false
    ),
    array(
        'id'          => '3',
        'name'        => 'Fried Wonton',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep fried Chicken & Prawn wraped wonton served with sweet chilli sauce',
        'price'       => '300',
        'image'       => $theme_uri . '/assets/menu/fried-wonton.png',
        'featured'    => false
    ),
    array(
        'id'          => '4',
        'name'        => 'Chicken Escalope Fry 8pcs',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '5',
        'name'        => 'Goan Chicken 6 Pcs',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '360',
        'image'       => $theme_uri . '/assets/menu/goan-chicken.png',
        'featured'    => false
    ),
    array(
        'id'          => '6',
        'name'        => 'Fried Prawn Finger Roll',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '380',
        'image'       => $theme_uri . '/assets/menu/fried-prawn-roll.png',
        'featured'    => false
    ),
    array(
        'id'          => '7',
        'name'        => 'Cox Fry Loitta',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => $theme_uri . '/assets/menu/cox-fry-loitta.png',
        'featured'    => false
    ),
    array(
        'id'          => '8',
        'name'        => 'Spicy Chicken With Cheese',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '9',
        'name'        => 'Thai Fried Chicken',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep Fried farm chicken served with thai spicy dipping sauce',
        'price'       => '620',
        'image'       => $theme_uri . '/assets/menu/thai-fried-chicken.png',
        'featured'    => false
    ),
    array(
        'id'          => '10',
        'name'        => 'Fish Finger',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '340',
        'image'       => $theme_uri . '/assets/menu/fish-finger.png',
        'featured'    => false
    ),
    array(
        'id'          => '11',
        'name'        => 'Calamari Fritters',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '120 gm',
        'description' => 'Deep Fried Calamari rings served with Tatar Sauce',
        'price'       => '400',
        'image'       => $theme_uri . '/assets/menu/calamari-fritters.png',
        'featured'    => false
    ),
    array(
        'id'          => '12',
        'name'        => 'Chicken Stream Momo',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '350',
        'image'       => $theme_uri . '/assets/menu/chicken-steam-momo.png',
        'featured'    => false
    ),
    array(
        'id'          => '13',
        'name'        => 'Garlic Mashroom With Garlic Bread',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => $theme_uri . '/assets/menu/garlic-mushroom.png',
        'featured'    => false
    ),
    array(
        'id'          => '14',
        'name'        => 'Thai Special Fried Chicken',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '600',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '15',
        'name'        => 'Crunchy Drums Wings',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep Fried crunchy wings served with chilli sauce',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '16',
        'name'        => 'Chinese Chicken Fry',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep Fried Crispy Chicken Served WithThai Spicy dipping Sauce',
        'price'       => '600',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '17',
        'name'        => 'Chicken Fried Wings',
        'category'    => 'Starter',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep Fried Chicken Wings Served Withhot tomato Sauce',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '18',
        'name'        => 'Crispy Fried Chicken',
        'category'    => 'Fast Food & Sandwith',
        'subCategory' => '',
        'quantity'    => '1 Pcs',
        'description' => 'Deep Fried farm chicken served with tomato sauce & french fries',
        'price'       => '160',
        'image'       => $theme_uri . '/assets/menu/crispy-fried-chicken.png',
        'featured'    => false
    ),
    array(
        'id'          => '19',
        'name'        => 'French Fries',
        'category'    => 'Fast Food & Sandwith',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Deep Fried French Fries served with Chef special sauce',
        'price'       => '170',
        'image'       => $theme_uri . '/assets/menu/french-fries.png',
        'featured'    => false
    ),
    array(
        'id'          => '20',
        'name'        => 'Buffalo Wings',
        'category'    => 'Fast Food & Sandwith',
        'subCategory' => '',
        'quantity'    => '6 Pcs',
        'description' => 'Deep Fried Chicken Toasted with Hot Creamy Chilli Sauce',
        'price'       => '360',
        'image'       => $theme_uri . '/assets/menu/buffalo-wings.png',
        'featured'    => false
    ),
    array(
        'id'          => '21',
        'name'        => 'Chicken Sandwich',
        'category'    => 'Fast Food & Sandwith',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Bread With Chicken & Mayo',
        'price'       => '97.2',
        'image'       => $theme_uri . '/assets/menu/chicken-sandwich.png',
        'featured'    => false
    ),
    array(
        'id'          => '22',
        'name'        => 'Smoked Chicken Sandwich',
        'category'    => 'Fast Food & Sandwith',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Toasted bread , BBQ chicken with vegetable & Mayo',
        'price'       => '280.8',
        'image'       => $theme_uri . '/assets/menu/smoked-chicken-sandwich.png',
        'featured'    => false
    ),
    array(
        'id'          => '23',
        'name'        => 'Keto Meal-Fish',
        'category'    => 'Keto Meal',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '24',
        'name'        => 'Keto Meal-Chicken',
        'category'    => 'Keto Meal',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '25',
        'name'        => 'Oven Baked Chicken',
        'category'    => 'Keto Meal',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '500',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '26',
        'name'        => 'Fresh Salad',
        'category'    => 'Salad',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '420',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '27',
        'name'        => 'Green Papaya Salad',
        'category'    => 'Salad',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '420',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '28',
        'name'        => 'Yum Talay (Seafood Salad)',
        'category'    => 'Salad',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Juicy mixed seafood salad with Prawn, squid, cuttle fish, crab, freshness of tomato, Onion, thai spice & Lamon juice.',
        'price'       => '750',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '29',
        'name'        => 'Chicken Cashew-nut salad',
        'category'    => 'Salad',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Crunchy Chicken, Tomato, Cucumber, OnionCoriander leaves, rice powder, spicy chilli saucetom yum paste,carnation milk & cashew-nut.',
        'price'       => '550',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '30',
        'name'        => 'Avanti Special Ramen',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '31',
        'name'        => 'Thai Soup 1:1',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'A thick / clear hot spicy & sour soup with Prawn, Chicken & mushroom.',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '32',
        'name'        => 'Thai Soup 1:3',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'A thick / clear hot spicy & sour soup with Prawn, Chicken & mushroom.',
        'price'       => '560',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '33',
        'name'        => 'Thai Steamboat Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '700',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '34',
        'name'        => 'Chicken Dumpling Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '35',
        'name'        => 'Special Steam Clear Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '36',
        'name'        => 'Cream Of Mashroom Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '750',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '37',
        'name'        => 'Chicken Vegetable Clear Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '520',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '38',
        'name'        => 'Chicken Onion Soup',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '560',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '39',
        'name'        => 'Seafood Soup 1:3',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'A thai spicy clear soup with prawn, squid, cuttle fish, crab, mushroomthai herbs & lemon juice',
        'price'       => '750',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '40',
        'name'        => 'Chicken Corn Soup 1:3',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Chicken Corn Soup with mineed chicken & duck egg drop.',
        'price'       => '420',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '41',
        'name'        => 'Chef Special Soup (1:3)',
        'category'    => 'Soup',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '660',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '42',
        'name'        => 'Chicken Pie',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '43',
        'name'        => 'American Chopci',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '450',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '44',
        'name'        => 'Pad Thai Noodles 1:1',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried noodles with egg , Prawn Or chicken',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '45',
        'name'        => 'Pad Thai Noodles 1:2',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried noodles with egg , Prawn Or chicken',
        'price'       => '520',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '46',
        'name'        => 'Sea Food Pad-Thai Nodules 1:2',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried chow mein with egg ,Chicken & prawn.',
        'price'       => '660',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '47',
        'name'        => 'Chicken Chaw-meain(1:2)',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '48',
        'name'        => 'Chef Special Chaw-meain(1:2)',
        'category'    => 'Noodles & Chow Mein',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '560',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '49',
        'name'        => 'Khaw Phat (Egg fried Rice) 1:3',
        'category'    => 'Rice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried rice with egg.',
        'price'       => '450',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '50',
        'name'        => 'Khaw Phat Khai (Chicken fried Rice) 1:3',
        'category'    => 'Rice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried rice with Chicken.',
        'price'       => '550',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '51',
        'name'        => 'Thai Fried Rice 1:3',
        'category'    => 'Rice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Thai style fried rice with Chicken',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '52',
        'name'        => 'Avanti Spicial Fried Rice 1:3',
        'category'    => 'Rice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried rice with Chicken, Prawn, Squid & Cuttle fish.',
        'price'       => '680',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '53',
        'name'        => 'Kung Pao Chicken 1:3',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried chicken with capsicum, dry chilli, spring onion, onion & nut.',
        'price'       => '550',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '54',
        'name'        => 'Chicken Bulgagi Curry',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '55',
        'name'        => 'Chicken sizzling 1:3',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried chicken with Onion, carrot, broccoli , Capsicum & spring onion.',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '56',
        'name'        => 'Foil Chicken Curry 1:3',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried chicken with hot chilli Sauce Onion, Carrot, Capsicum & Spring Onion',
        'price'       => '550',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '57',
        'name'        => 'Chicken Masala Curry 1:3',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried chicken with mushroom, bosil leaves cacked in a traditional chinese style.',
        'price'       => '560',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '58',
        'name'        => 'Turkish Chicken With Creamy Sauce',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '600',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '59',
        'name'        => 'Chicken Vegetables With Garlic Sauce',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '550',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '60',
        'name'        => 'Long Bean Chicken Curry',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '580',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '61',
        'name'        => 'Chicken Chilli Curry 1:3',
        'category'    => 'Chicken',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '600',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '62',
        'name'        => 'Beef Sizzling',
        'category'    => 'Beef & Mutton',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Strip cut beef Onion, Capsicum served on a hot sizzling Plate',
        'price'       => '650',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '63',
        'name'        => 'Boneless Beef With Cashew-nut',
        'category'    => 'Beef & Mutton',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '620',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '64',
        'name'        => 'Beef Bulgagi Curry',
        'category'    => 'Beef & Mutton',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '620',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '65',
        'name'        => 'Beef Ginger Mashroom',
        'category'    => 'Beef & Mutton',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Beef cooked with garlic & Pepper',
        'price'       => '650',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '66',
        'name'        => 'Mutton Masala',
        'category'    => 'Beef & Mutton',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Mutton Cooked With masala style gravy',
        'price'       => '800',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '67',
        'name'        => 'Kung Pad Prik Sod (Prawn chilli onion) 1:3',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried prawn with chilli , onion.',
        'price'       => '560',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '68',
        'name'        => 'Fried Prawn Masala',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried prawn with garlic & pepper.',
        'price'       => '590',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '69',
        'name'        => 'Prawn Sizzling 1:3',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried prawn with onion,capsicum, carrot, broccoli & spring onion.',
        'price'       => '650',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '70',
        'name'        => 'Whole Grill Red Snapper Fish (Per 100gm)',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '220',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '71',
        'name'        => 'Whole Steam Fish With Lemon Butter Sauce',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '220',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '72',
        'name'        => 'Fish Mandarian',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '520',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '73',
        'name'        => 'Fried Pomfret 1:3',
        'category'    => 'Sea Food',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Steam silver pomfret top on a Chef special lime sauce.',
        'price'       => '750',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '74',
        'name'        => 'Pad pak Ruam (Thai mixed vegitable) 1:3',
        'category'    => 'Vegetable',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried thai mixed vegitable with chicken, prawn,capsicum,mushroom, coli flower,broccoli,carrot, long been,cabbage,green peas, baby corn & bean sprouts.',
        'price'       => '500',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '75',
        'name'        => 'Jirou shucai zhingguo (Chinese vegitable with chicken) 1:3',
        'category'    => 'Vegetable',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Stir fried vegitable with chicken taste of Chaina.',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '76',
        'name'        => 'Oven Baked Pasta',
        'category'    => 'Pasta',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Oven baked creamy chicken penne pasta topped with mozzarella cheese.',
        'price'       => '380',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '77',
        'name'        => 'Fettuccine Alfredo',
        'category'    => 'Pasta',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '78',
        'name'        => 'Oven Baked Naga Pasta',
        'category'    => 'Pasta',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Oven baked creamy chicken penne pasta with Naga.',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '79',
        'name'        => 'Mac & Cheese With Fries',
        'category'    => 'Pasta',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Overload creamy mac & cheese pasta served with garlic bread.',
        'price'       => '420',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '80',
        'name'        => 'Crispy Chicken Burger',
        'category'    => 'Premium Burger',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => $theme_uri . '/assets/menu/crispy-chicken-burger.png',
        'featured'    => false
    ),
    array(
        'id'          => '81',
        'name'        => 'Cheese Volcano',
        'category'    => 'Premium Burger',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '270',
        'image'       => $theme_uri . '/assets/menu/cheese-volcano.png',
        'featured'    => false
    ),
    array(
        'id'          => '82',
        'name'        => 'Cok Cok Smoky Burger',
        'category'    => 'Premium Burger',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Smoky grill chicken , cheese, lettuce, tomato, Onion & smoky mayo.',
        'price'       => '280',
        'image'       => $theme_uri . '/assets/menu/cok-cok-smoky-burger.png',
        'featured'    => false
    ),
    array(
        'id'          => '83',
        'name'        => 'Naga Burger',
        'category'    => 'Premium Burger',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => $theme_uri . '/assets/menu/naga-burger.png',
        'featured'    => false
    ),
    array(
        'id'          => '84',
        'name'        => 'Meat Pressure Burger',
        'category'    => 'Premium Burger',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Grill chicken , grill sausage, smok cold cut chicken, cheese, lettuce, Onion & chef special mayo.',
        'price'       => '380',
        'image'       => $theme_uri . '/assets/menu/meat-pressure-burger.png',
        'featured'    => false
    ),
    array(
        'id'          => '85',
        'name'        => 'Cheese Lovers',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => 'The right Mix Of Mozzarella Cheese with mother Sauce',
        'price'       => '580',
        'image'       => $theme_uri . '/assets/menu/cheese-lovers-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '86',
        'name'        => 'Cheese Lovers',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => 'The right Mix Of Mozzarella Cheese with mother Sauce',
        'price'       => '720',
        'image'       => $theme_uri . '/assets/menu/cheese-lovers-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '87',
        'name'        => 'Vegetaable margerita Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => '',
        'price'       => '690',
        'image'       => $theme_uri . '/assets/menu/vegetable-margherita-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '88',
        'name'        => 'Vegetaable margerita Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => '',
        'price'       => '850',
        'image'       => $theme_uri . '/assets/menu/vegetable-margherita-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '89',
        'name'        => 'Spicy Beef Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => '',
        'price'       => '700',
        'image'       => $theme_uri . '/assets/menu/spicy-beef-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '90',
        'name'        => 'Spicy Beef Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => '',
        'price'       => '880',
        'image'       => $theme_uri . '/assets/menu/spicy-beef-pizza.png',
        'featured'    => false
    ),
    array(
        'id'          => '91',
        'name'        => 'Sausage Delight',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => '',
        'price'       => '700',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '92',
        'name'        => 'Sausage Delight',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => '',
        'price'       => '880',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '93',
        'name'        => 'Chicken Overloaded',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => '',
        'price'       => '690',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '94',
        'name'        => 'Chicken Overloaded',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => '',
        'price'       => '860',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '95',
        'name'        => 'Texas Mix Masala',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => 'Grilled chicken, sausage, chilli, jalapeno, sweet corn, oliv, & cheese.',
        'price'       => '760',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '96',
        'name'        => 'Texas Mix Masala',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => 'Grilled chicken, sausage, chilli, jalapeno, sweet corn, oliv, & cheese.',
        'price'       => '900',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '97',
        'name'        => 'Chicken Exotica',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => 'Combined with marineted chicken, mozzarella cheese,mother sauce, Mashroom, Capsicum, Onion & Vegetable',
        'price'       => '760',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '98',
        'name'        => 'Chicken Exotica',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => 'Combined with marineted chicken, mozzarella cheese,mother sauce, Mashroom, Capsicum, Onion & Vegetable',
        'price'       => '930',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '99',
        'name'        => 'Avanti Special Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'M',
        'description' => 'Combined with BBQ chicken, marineted chicken full of mozzarella cheese,mother sauce, black oliv, Capsicum, Onion & Vegetable',
        'price'       => '800',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '100',
        'name'        => 'Avanti Special Pizza',
        'category'    => 'Pizza',
        'subCategory' => '',
        'quantity'    => 'L',
        'description' => 'Combined with BBQ chicken, marineted chicken full of mozzarella cheese,mother sauce, black oliv, Capsicum, Onion & Vegetable',
        'price'       => '950',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '101',
        'name'        => 'French Fries',
        'category'    => 'Kids & Snacks',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Deep fried fries served with mayo.',
        'price'       => '180',
        'image'       => $theme_uri . '/assets/menu/french-fries.png',
        'featured'    => false
    ),
    array(
        'id'          => '102',
        'name'        => 'Kids Chicken Sandwich',
        'category'    => 'Kids & Snacks',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '65',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '103',
        'name'        => 'Peri Peri Chicken',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '104',
        'name'        => 'Teriyaki Chicken',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '105',
        'name'        => 'Rupchanda Fish',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Thai Fried Rice,Rupchanda Fry,Chicken Strips,Lemon Sauce,Chinese Vegetable & Cole-slaw Salad',
        'price'       => '440',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '106',
        'name'        => 'BBQ Chicken Meal With Curry',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Thai Fried Rice,Potato Wages,Sweet & Sour Chicken Curry,B.B.Q Chicken,Mixed Vegetable & Cole-slaw Salad',
        'price'       => '450',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '107',
        'name'        => 'Masala Time',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Masala Rice,Fried Chicken,MasalaChicken Curry,Chinese Vegetable & Cole-slaw Salad',
        'price'       => '425',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '108',
        'name'        => 'Chicken Boustead with Drum Stick',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Fried Rice,Chicken Boustead,Drum Stick,Juicy Wings,Mixed Vegetable,Cole-slaw Salad & Pickle Sauce',
        'price'       => '425',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '109',
        'name'        => 'Fried Chicken Meal',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Fried Rice,Crispy Fried Chicken ,Chinese Vegetable & Fresh Salad',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '110',
        'name'        => 'Avanti Special Meal',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => 'Served With Fried Rice,Crispy Fried Chicken 1pcs,Chilli Chicken 1pcs, Chinese Vegetable & Fresh Salad',
        'price'       => '360',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '111',
        'name'        => 'Dori Fish Platter',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '390',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '112',
        'name'        => 'Chicken Streak',
        'category'    => 'Platters',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '113',
        'name'        => 'Espresso',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '140',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '114',
        'name'        => 'Espresso',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '190',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '115',
        'name'        => 'Americano',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '150',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '116',
        'name'        => 'Americano',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '220',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '117',
        'name'        => 'Cappuchino',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '118',
        'name'        => 'Cappuchino',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '260',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '119',
        'name'        => 'Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '120',
        'name'        => 'Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '260',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '121',
        'name'        => 'Caramel Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '122',
        'name'        => 'Caramel Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '123',
        'name'        => 'Hazlenut Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '124',
        'name'        => 'Hazlenut Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '125',
        'name'        => 'Hot Chocolate',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '190',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '126',
        'name'        => 'Hot Chocolate',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '127',
        'name'        => 'Macchiato',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '150',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '128',
        'name'        => 'Macchiato',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '129',
        'name'        => 'Hot Mocha',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '270',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '130',
        'name'        => 'Hot Mocha',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '131',
        'name'        => 'Affogato',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '190',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '132',
        'name'        => 'Affogato',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '260',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '133',
        'name'        => 'Vanilla Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Regular',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '134',
        'name'        => 'Vanilla Latte',
        'category'    => 'Hot Coffee',
        'subCategory' => '',
        'quantity'    => 'Large',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '135',
        'name'        => 'Iced Americano',
        'category'    => 'Over Iced Latte',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '180',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '136',
        'name'        => 'Iced Mocha',
        'category'    => 'Over Iced Latte',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '137',
        'name'        => 'Iced Vanilla latte',
        'category'    => 'Over Iced Latte',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '138',
        'name'        => 'Iced Caramel Macchiato',
        'category'    => 'Over Iced Latte',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '139',
        'name'        => 'Blueberry Smoothie',
        'category'    => 'Smoothies',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '270',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '140',
        'name'        => 'Kiwi Smoothie',
        'category'    => 'Smoothies',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '270',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '141',
        'name'        => 'Mango Smoothie',
        'category'    => 'Smoothies',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '250',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '142',
        'name'        => 'Mint Lemonade',
        'category'    => 'Lemonade',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '143',
        'name'        => 'Kiwi Lemonade',
        'category'    => 'Lemonade',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '250',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '144',
        'name'        => 'Peach Lemonade',
        'category'    => 'Lemonade',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '260',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '145',
        'name'        => 'Hazlenut Freppe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '146',
        'name'        => 'Hazlenut Mocha Freppe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '350',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '147',
        'name'        => 'Caramel Freppe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '300',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '148',
        'name'        => 'Mocha Freppe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '320',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '149',
        'name'        => 'Brownie Mocha Frappe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '400',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '150',
        'name'        => 'Cookies & Cream Frappe',
        'category'    => 'Cold Coffee Freppe',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '280',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '151',
        'name'        => 'Blue Ocean',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '230',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '152',
        'name'        => 'Virgin Mojito',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '230',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '153',
        'name'        => 'Sunset Moctail',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '250',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '154',
        'name'        => 'Kiwi Mojito',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '155',
        'name'        => 'Strawberry Moctail',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '230',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '156',
        'name'        => 'Purpel Huzz',
        'category'    => 'Moctail',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '250',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '157',
        'name'        => 'Orange Juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '190',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '158',
        'name'        => 'Papaya Juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '160',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '159',
        'name'        => 'Pinapple juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '160',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '160',
        'name'        => 'Mango Juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '160',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '161',
        'name'        => 'Apple Juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '220',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '162',
        'name'        => 'Seasonal Juice',
        'category'    => 'Juice',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '-',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '163',
        'name'        => 'Sweet Lassi',
        'category'    => 'Lassi',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '160',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '164',
        'name'        => 'Salt Lassi',
        'category'    => 'Lassi',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '140',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '165',
        'name'        => 'Mango Lassi',
        'category'    => 'Lassi',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '166',
        'name'        => 'Strawberry Lassi',
        'category'    => 'Lassi',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '167',
        'name'        => 'Oreo Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '168',
        'name'        => 'Nutella Chocolate Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '260',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '169',
        'name'        => 'Vanilla Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '170',
        'name'        => 'Chocolate Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '171',
        'name'        => 'Strawberry Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '172',
        'name'        => 'Mango Shake',
        'category'    => 'Milk Shake',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '240',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '173',
        'name'        => 'Mango Marvel',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '180',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '174',
        'name'        => 'Ambrasia',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '175',
        'name'        => 'Black Frost',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '176',
        'name'        => 'Butter Scotch',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '177',
        'name'        => 'Chocolate',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '180',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '178',
        'name'        => 'Strawberry',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '180',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '179',
        'name'        => 'Vanilla',
        'category'    => 'Ice-Cream',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '180',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '180',
        'name'        => 'Caramel Pudding',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '110',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '181',
        'name'        => 'Red Velvet',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '175',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '182',
        'name'        => 'Orea Chesse Cake',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '220',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '183',
        'name'        => 'Chocolate Delight',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '184',
        'name'        => 'Chocolate Brownie with Ice-Cream',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '200',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '185',
        'name'        => 'Chocolate Sizzling Brownie with Ice-Cream',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '250',
        'image'       => '',
        'featured'    => false
    ),
    array(
        'id'          => '186',
        'name'        => 'Sweet & Sour Yogurt',
        'category'    => 'Dessert',
        'subCategory' => '',
        'quantity'    => '',
        'description' => '',
        'price'       => '80',
        'image'       => '',
        'featured'    => false
    )
);
?>